### ISSUE TITLE
Integration attempts to retrieve task data with wrong email address

### ISSUE THREAD

**Issue by DaniChristiaans** [chrisyarbrough/CodecksPlasticIntegration#6]
The integration seems to work fine in the current version of Unity DevOps Version Control (previously PlasticSCM), but there is some behaviour that seems unintended.

My setup:
Logged into Unity Version Control with my Unity ID, with email address A.
Codecks account uses email address B. I entered this into the Preferences > Issue Trackers window inside UVCS/Plastic according to the image shown at point 4 of Getting Started in the integration readme.

The integration seems to attempt to fetch the task data from Codecks using email address A, instead of email address B. It then returns an error, stating "Failed to find user by mail: [email address A]". I believe that the integration should not be using email address A here, but instead should use email address B as entered in the Preferences > Issue Trackers window.

My colleague uses only 1 email address for all of this, and for him the integration works as expected.

Thanks in advance!

**Comment by chrisyarbrough** [comment]
Thanks for bringing this up! Sorry for not being quicker, I kind of didn't have notifications enabled. ^^
Anyway, I'll set the project up to work on macOS first, so I can work on it again.

**Comment by chrisyarbrough** [comment]
I can confirm the issue on macOS, Unity DevOps 11.0.16.9080.
Logged in with my Unity ID.
Setup a Codecks account with a different mail.
When I try to create branch it says "Failed to find user by mail: xxx" where the mail is my Unity ID and not the intended Codecks mail which was set up in the settings.

**Comment by DaniChristiaans** [comment]
No problem! I circumvented the issue on my side by changing the email address associated with my Unity ID to the same company email address I already used for Plastic.

That opened up a whole other can of worms on Unity's side (losing access to my admin account and all my invoices) but fortunately Unity support helped me resolve that.

**Comment by chrisyarbrough** [comment]
Glad to hear, I'll keep this one open and try to find a solution nevertheless. Feel free to unsub if you feel spammed. :)

One possible **workaround** (for other users that might be reading) at the moment: In the CreateBranch window, there's an option called _Display pending tasks from all users_. That will at least show the entire task list, which then can be filtered by issue title or assignee (email).

<img width="831" alt="image" src="https://github.com/user-attachments/assets/b3b20dda-1bb3-4756-8e87-ab39e6cb1eca" />

Now the **issue**:
In the API, Plastic passes us the "assigneeEmail" which the extension is supposed to use for filtering the list of tasks. However, the passed assignee is the one from Plastic/Unity. So yea, they assume that the account in Plastic is the same as in the issue tracker.

I think I found a solution though: I can simply use the email that is configured via the extension settings (we need that anyway to use the Codecks API). Will test some more and prepare the fix release soon.
