### ISSUE TITLE
Creating branches using "From Task" tab displays closed / done issues.

### ISSUE THREAD

**Issue by gabzzel** [chrisyarbrough/CodecksPlasticIntegration#7]
As the title says, whenever I create a branch and use the "From Task" tab, it displays all issues, regardless of status. 
I assume this is unintended behaviour, as done tasks (in Codecks) should not have a branch assignable to them in order to preserve proper workflow.

**Comment by chrisyarbrough** [comment]
Thanks for letting me know! I can reproduce the issue. I agree, it would be better to filter-out the "done" cards. I'll get on it. There should be at least two ways to fix this: remove status "done" cards via the query sent to Codecks or by filtering them from the response.

**Comment by chrisyarbrough** [comment]
Fixed in v1.5.
https://github.com/chrisyarbrough/CodecksPlasticIntegration/releases/tag/v.1.5
